apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-zapatillas
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web
    spec:
      containers:
      - name: servidor-web
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.puerto }} 
        resources:
          limits:
            cpu: {{ .Values.cpuLimit }}
            memory: {{ .Values.memoryLimit }}
          requests:
            cpu: "50m"
            memory: "64Mi"
